POST http://localhost:8081/api/vote
accept: */*
Content-Type: application/json

{
  "voteFormId": "9aed42",
  "selectedOptions": [{"title": "option1","type": "TEXT", "input": "option1 input"}],
  "voteAt": "2024-02-06T12:34:56.789"
}

###
GET http://localhost:8081/api/vote/47d8da