server:
  port: 8081

spring:
  application:
    name: be
  profiles:
    include: data

  security:
    oauth2:
      client:
        registration:
          google:
            clientName: "Google"
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
